name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
          php: [7.3, 7.4]

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php }}"

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      # --no-plugins avoid to install grumphp's git hook
      run: composer install 

    - name: Run GrumPhp lints
      run: ./vendor/bin/grumphp run --testsuite=lint

    - name: Run GrumPhp tests
      run: ./vendor/bin/grumphp run --testsuite=tests
