##########
# GITHUB #
##########

# Current workflow
# https://github.com/cylmat/phpconfig/actions

# DOC
# https://github.com/actions/starter-workflows/

name: PHP Config

on:
  push:
    branches: [ main, dev, codeception ]

###
# Jobs
###
jobs:
  run:
    # Set in repo's "Settings/Environments"
    environment: Codecov
    
    runs-on: ubuntu-latest
    name: Lint, tests, cover, build, deploy
    strategy:
      fail-fast: false
      matrix:
          php: [7.3, 7.4]

    steps:
    - uses: actions/checkout@v2

    # Php, composer, ext, xdebug
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: xdebug
        extensions: mbstring, intl
        php-version: "${{ matrix.php }}"

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      # --no-plugins avoid to install grumphp's git hook
      run: composer install --prefer-dist --no-progress --no-plugins

    ###########
    # LINTING #
    ###########
    - name: Run GrumPhp lint
      run: make grump-lint

    ###########
    # TESTING #
    ###########
    - name: Run GrumPhp tests
      run: make grump-tests

    ############
    # BEHAVIOR #
    ############
    - name: Run GrumPhp behavior
      run: |
        sudo cest/server.sh --run
        make grump-behav
        sudo cest/server.sh --stop

    ############
    # COVERAGE #
    ############
    - name: Codecov coverage
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        ./vendor/bin/phpunit --coverage-filter src --coverage-clover coverage.xml
        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

    ###########
    # BUILDER #
    ###########

    - name: Phing builder
      run: |
        make phing-bin
        make phing

    ############
    # DEPLOYER #
    ############
    - name: Deploy code
      env: 
        VCS_REPOSITORY: ${{ secrets.VCS_REPOSITORY }}
      run: |
        make deployer-bin
        make deployer